# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 65%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "benches/"
  - "examples/"
